name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x] # Stable Node.js versions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Debug repository files
        run: |
          echo "Current directory structure:"
          pwd
          ls -al

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps || npm ci --legacy-peer-deps

      - name: Start application
        run: npm start
